argo-cd:
  global:
    domain: argocd.lancebramsey.com
  cluster:
    inClusterEnabled: false
  configs:
    cm:
      kustomize.buildOptions: --enable-helm
  crds:
    keep: false
  server:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
        #nginx.ingress.kubernetes.io/app-root: /login
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      enabled: true
      tls: true
      extraTls:
      - hosts:
        - argocd.lancebramsey.com
        secretName: argocd.lancebramsey.com-tls
      hostname: argocd.lancebramsey.com
      ingressClassName: nginx
