kargo:
  api:
    host: kargo.lancebramsey.com
    secret:
      name: kargo-admin
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      enabled: false
      ingressClassName: nginx
      tls: 
        enabled: true
        selfSignedCert: true
