kargo:
  api:
    secret:
      name: kargo-admin
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
        #nginx.ingress.kubernetes.io/app-root: /login
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      enabled: true
      tls: true
      extraTls:
      - hosts:
        - kargo.lancebramsey.com
        secretName: kargo.lancebramsey.com-tls
      hostname: kargo.lancebramsey.com
      ingressClassName: nginx
