cluster:
  inClusterEnabled: false
configs:
  cm:
    kustomize.buildOptions: --enable-helm
global:
  domain: argocd.server.local
server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      nginx.ingress.kubernetes.io/app-root: /login
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    enabled: true
    extraTls:
    - hosts:
      - argocd.server.local
      secretName: argocd.server.local-tls
    hostname: argocd.server.local
    ingressClassName: nginx
