prometheusOperator:
  admissionWebhooks:
    certManager: 
      enabled: true
prometheus:
  ingress: 
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer 
    hosts:
      - prometheus.lancebramsey.com
    tla:
      - secretName: prometheus-general-tls
        hosts:
          - prometheus.lancebramsey.com
  prometheusSpec:
    externalUrl: "https://prometheus.lancebramsey.com/"

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer 
    hosts:
      - alertmanager.lancebramsey.com
    tla:
      - secretName: alertmanager-general-tls
        hosts:
          - alertmanager.lancebramsey.com
grafana:
  enabled: false
