apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Bravesguy18/argocd.git
              revision: HEAD
              directories:
                - path: infrastructure/*
          - clusters: {} 
            #selector:
              #matchLabels:
                #project: gccs
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        function: infrastructure
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/Bravesguy18/argocd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: '{{.name}}'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
