apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-to-all-clusters
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Bravesguy18/argocd.git
              revision: HEAD
              directories:
                - path: infrastructure/*/argocd
          - clusters: 
              selector:
                matchLabels:
                  project: gccs
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Bravesguy18/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: '{{name}}'
        namespace: default
