apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argo-cd
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/Bravesguy18/argocd.git
    targetRevision: HEAD
    path: infrastructure/test-app/base

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
