apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-nothing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-nothing
  template:
    metadata:
      labels:
        app: do-nothing
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sleep", "infinity"]
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
